# To create a user for this webapp, run the following from PG's SQL console:
#
#   CREATE USER arachni WITH PASSWORD 'secret' CREATEDB;
#
# (Update the credentials in both the above SQL query and the bellow settings appropriately.)

development:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev

# test: 
  # adapter: postgresql
  # host: localhost
  # username: user
  # database: app-dev

production:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev

cucumber:
  <<: *test
