# To create a user for this webapp, run the following from PG's SQL console:
#
#   CREATE USER arachni WITH PASSWORD 'secret' CREATEDB;
#
# (Update the credentials in both the above SQL query and the bellow settings appropriately.)

development:
  adapter: postgresql
  database: postgres
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: postgres
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: postgres
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
