# To create a user for this webapp, run the following from PG's SQL console:
#
#   CREATE USER arachni WITH PASSWORD 'secret' CREATEDB;
#
# (Update the credentials in both the above SQL query and the bellow settings appropriately.)

development:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev

test: 
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: arachni_test
  pool: 50
  username: arachni
  password: secret

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: arachni_production
  pool: 50
  username: arachni
  password: secret

cucumber:
  <<: *test
